os:
  - linux

language: shell

env:
  global:
    - IMAGE=penitence/helm-kubectl-client
  jobs:
    - TAG=1.0.2 BASE_IMAGE=alpine:3.9 helm_version=3.0.2
    - TAG=1.0.2-jre BASE_IMAGE=openjdk:8-alpine3.9 helm_version=3.0.2
    - TAG=latest BASE_IMAGE=alpine:3.9 helm_version=3.0.2

services:
  - docker

script:
  - docker build --build-arg BASE_IMAGE=$BASE_IMAGE --build-arg helm_version=$helm_version -t $IMAGE:$TAG .

after_success:
  - docker login -u="$USERNAME" -p="$PASSWORD"
  - docker push $IMAGE:$TAG
